[package]
name = "dipc"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.2", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
image = "0.24.6"
deltae = "0.3.1"
lab = "0.11.0"
